config/routes.rb
Vega::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
  resources :explores
  get '/educators/plan' => 'educators#plan'
  get '/educators/teach' => 'educators#teach'

  post '/getBooksSearchResults' => 'books#getSearchResults'
  resources :books

  get '/contact' => 'home#contact'
  get '/setLanguage' => 'home#setLanguage'
  get '/history' => 'home#history'

  get '/admin' => 'admin#index'
  get '/admin/educators/plan' => 'admin#editEducatorsPlan'
  post '/admin/educators/plan/addNews' => 'admin#addNews'
  delete '/admin/educators/plan/removeNews/:id' => 'admin#removeNews'
  post '/admin/educators/plan/addTeacherComment' => 'admin#addTeacherComment'
  delete '/admin/educators/plan/removeTeacherComment/:id' => 'admin#removeTeacherComment'

  get '/admin/educators/teach' => 'admin#editEducatorsTeach'
  post '/admin/educators/teach/editEducationalOutcome' => 'admin#editEducationalOutcome'
  post '/admin/educators/teach/addResource' => 'admin#addResource'
  delete '/admin/educators/teach/removeResource/:id' => 'admin#removeResource'
  

  scope '/admin' do
    resources :cards do
      member do
        post 'uploadAttachment'
        delete 'removeAttachment'
        post 'addQuizz'
        delete 'removeQuizz'
        post 'addFunFact'
        delete 'removeFunFact'
        post 'addComment'
      end
    end
  end
  get '/cards/:id/openInfoModal' => 'cards#openInfoModal'
  
  

end

app/models/card.rb
class Card < ActiveRecord::Base
	has_many :node_attachments, :as => :nodeable, :dependent => :destroy
  	has_many :attachments, :through => :node_attachments, class_name: "Attachment"

  	has_many :comments

  	has_many :funFacts

  	has_many :quizzs

	def self.language(lang)
		where(:language => lang)
	end

	def self.bookOfKnowledge()
		where(:bookOfKnowledge => true)
	end

	def self.educators()
		where(:educators => true)
	end

	def self.search(search)
		if search
			where('name LIKE ?', "%#{search}%")
		else
			where("")
		end
	end

	# input genre is string
	def self.getGenre(genre)
		if genre == "all"
			where("")
		else
			where(:genre => genre.split(","))
		end
		
	end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy, :openInfoModal, :uploadAttachment, :addComment, :addQuizz, :addFunFact]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render action: 'show', status: :created, location: @card }
      else
        format.html { render action: 'new' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end

  def openInfoModal
    if @card.genre == "activities"
      render :partial => "/cards/popUps/activity"
    elsif ["flora","fauna","sites"].include?(@card.genre)
      render :partial => "/cards/popUps/info"
    elsif ["webcam","games"].include?(@card.genre)
      render :partial => "/cards/popUps/extra"
    elsif ["trail","snorkel"].include?(@card.genre)
      render :partial => "/cards/popUps/trail"
    end
  end

  def uploadAttachment
    if !params[:upload].blank?
      attachment = @card.attachments.create(:file_name => params[:upload], :url => params[:upload], :user_id => current_user.id)
    end

    redirect_to(:back)
  end

  def removeAttachment
    attachment = Attachment.find(params[:id])
    attachment.nodeAttachments.destroy
    attachment.destroy

    redirect_to(:back)
  end

  def addQuizz
    @card.quizzs.create(description: params[:description], trueAnswer: params[:trueAnswer], falseAnswer1: params[:falseAnswer1], falseAnswer2: params[:falseAnswer2], falseAnswer3: params[:falseAnswer3], language: "es", active: true)
    redirect_to(:back)
  end

  def removeQuizz
    Quizz.find(params[:id]).destroy
    redirect_to(:back)
  end

  def addFunFact
    @card.funFacts.create(description: params[:description], language: "es", active: true)
    redirect_to(:back)
  end

  def removeFunFact
    FunFact.find(params[:id]).destroy
    redirect_to(:back)
  end

  def addComment
    @card.comments.create(:comment => params[:comment], :user_id => current_user.id)
    
    redirect_to(:back)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:name, :description, :genre, :bookOfKnowledge, :educators, :language)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for @card, :html => { :class => 'form' } do |f| %>
  <div class="form-group">
    <%= f.label :language, :class => 'control-label' %>
    <%= f.select :language, options_for_select([ ["Spanish","es"], ["English","en"] ], @card.language), {}, {:class => 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label' %>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label' %>
    <%= f.text_area :description, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :genre, :class => 'control-label' %>
    <%= f.select :genre, options_for_select([ ["Webcams","webcams"], ["Flora","flora"], ["Fauna","fauna"], ["Activities","activities"], ["Trails","trails"], ["Sites","sites"], ["Games","games"] ], @card.genre), {}, {:class => 'form-control'} %>
  </div>
  <div class="checkbox">
    <label>
      <%= f.check_box :bookOfKnowledge %> Show in book of knowledge?
    </label>
  </div>
  <div class="checkbox">
    <label>
      <%= f.check_box :educators %> Show in educators?
    </label>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cards_path, :class => 'btn btn-default' %>
  </div>
<% end %>

<h3>Attachments</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th><%= t(:name) %></th>
      <th><%= t(:photo) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @card.attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.id %></td>
        <td><%= attachment.file_name %></td>
        <td style="width: 50%" class="text-justify"><%= attachment.getPhoto(105,105).html_safe %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      removeAttachment_card_path(attachment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- Button trigger modal -->
<button class="btn btn-primary" data-toggle="modal" data-target="#uploadAttachmentModal">
Subir nueva foto
</button>

<!-- Modal -->
<%= form_tag 'uploadAttachment', :multipart => true, :type => :post do %>
<div class="modal fade" id="uploadAttachmentModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">SUBE TU IMAGEN O VÍDEO</h4>
      </div>
      <div class="modal-body">
        <%= file_field_tag "upload", :class => "file_modalupload_input" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag 'Subir Foto', :class => "btn btn-primary file_modalupload_button" %>
      </div>
    </div>
  </div>
</div>
<% end %>

<!-- QUIZZ -->
<h3>Quizz</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th><%= t(:Description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @card.quizzs.each do |quizz| %>
      <tr>
        <td><%= quizz.id %></td>
        <td><%= quizz.description %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      "/admin/cards/"+quizz.id.to_s+"/removeQuizz",
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- Button trigger modal -->
<button class="btn btn-primary" data-toggle="modal" data-target="#addQuizzModal">
Crear un nuevo quizz
</button>

<!-- Modal -->
<%= form_tag 'addQuizz', :multipart => true, :type => :post do %>
<div class="modal fade" id="addQuizzModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Crear un nuevo quizz</h4>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <label for="title">Description</label>
          <%= text_area_tag :description, nil, :class => 'form-control' %>
        </div>
        <div class="form-group">
          <label for="title">True answer</label>
          <%= text_area_tag :trueAnswer, nil, :class => 'form-control' %>
        </div>
        <div class="form-group">
          <label for="title">False answer 1</label>
          <%= text_area_tag :falseAnswer1, nil, :class => 'form-control' %>
        </div>
        <div class="form-group">
          <label for="title">False answer 2</label>
          <%= text_area_tag :falseAnswer2, nil, :class => 'form-control' %>
        </div>
        <div class="form-group">
          <label for="title">False answer 3</label>
          <%= text_area_tag :falseAnswer3, nil, :class => 'form-control' %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <%= submit_tag 'Crear quizz', :class => "btn btn-primary file_modalupload_button" %>
      </div>
    </div>
  </div>
</div>
<% end %>


<!-- Fun Facts -->
<h3>Fun Facts</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th><%= t(:Description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @card.funFacts.each do |funFact| %>
      <tr>
        <td><%= funFact.id %></td>
        <td><%= funFact.description %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      "/admin/cards/"+funFact.id.to_s+"/removeFunFact",
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- Button trigger modal -->
<button class="btn btn-primary" data-toggle="modal" data-target="#addFunFactModal">
Crear un nuevo fun fact
</button>

<!-- Modal -->
<%= form_tag 'addFunFact', :multipart => true, :type => :post do %>
<div class="modal fade" id="addFunFactModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Crear un nuevo fun fact</h4>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <label for="title">Description</label>
          <%= text_area_tag :description, nil, :class => 'form-control' %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <%= submit_tag 'Crear fun fact', :class => "btn btn-primary file_modalupload_button" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/cards/_popUpsPackage.html.erb
<!-- infoModal -->
<div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
<script type="text/javascript">
	function openInfoModal(card_id) {
		$('#infoModal').load('/cards/'+card_id+'/openInfoModal',function(result){
		    $('#infoModal').modal({show:true});
		});
	}
</script>

app/views/cards/edit.html.erb
<%= render partial: "/admin/menu" %>
<%- model_class = Card -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cards/index.html.erb
<%= render partial: "/admin/menu" %>
<%- model_class = Card -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:genre) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= link_to card.id, card_path(card) %></td>
        <td><%= card.name %></td>
        <td style="width: 50%" class="text-justify"><%= card.description %></td>
        <td><%= card.genre %></td>
        <td><%= distance_of_time_in_words_to_now(card.created_at) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_card_path(card), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      card_path(card),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_card_path,
            :class => 'btn btn-primary' %>

app/views/cards/new.html.erb
<%= render partial: "/admin/menu" %>
<%- model_class = Card -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cards/show.html.erb
<%= render partial: "/admin/menu" %>
<%- model_class = Card -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @card.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @card.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:genre) %>:</strong></dt>
  <dd><%= @card.genre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:language) %>:</strong></dt>
  <dd><%= @card.language %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bookOfKnowledge) %>:</strong></dt>
  <dd><%= @card.bookOfKnowledge %></dd>
  <dt><strong><%= model_class.human_attribute_name(:educators) %>:</strong></dt>
  <dd><%= @card.educators %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              cards_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_card_path(@card), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              card_path(@card),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>